version: '3.8'
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_ROOT_PASSWORD}@postgredb:${POSTGRES_DOCKER_PORT}/${POSTGRES_DATABASE}
    depends_on:
      - postgredb
    volumes:
      - ./packages/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules

  postgredb:
    image: postgres:16.4
    restart: unless-stopped
    env_file: packages/backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
